name: Deploy to Development

on:
  push:
    branches:
      - develop  # Chạy workflow khi có thay đổi trên nhánh `develop`
  pull_request:
    branches:
      - develop  # Chạy workflow khi có PR từ bất kỳ nhánh nào vào nhánh `develop`

jobs:
  deploy_development:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Cài đặt Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Bước 3: Cài đặt Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Kiểm tra Docker Compose đã được cài đặt

      # Bước 4: Xây dựng và chạy Docker containers cho môi trường Development
      - name: Build and run Docker containers for Development
        run: |
          docker-compose -f docker-compose-development.yml up --build -d  # Xây dựng và chạy Docker Compose cho môi trường Development

      # Bước 5: Chạy các bài kiểm tra (unit tests)
      - name: Run tests
        run: |
          docker exec -t backend yarn test  # Chạy kiểm tra trong container backend

      # Bước 6: Dừng các Docker containers sau khi hoàn thành
      - name: Stop Docker containers
        run: docker-compose -f docker-compose-development.yml down  # Dừng và xóa các container sau khi hoàn thành

      # Bước 7: Triển khai (Deploy) lên môi trường Development
      - name: Deploy to Development
        run: |
          echo "Deploying to Development environment"
        env:
          DEV_API_KEY: ${{ secrets.DEV_API_KEY }}  # Sử dụng DEV_API_KEY từ GitHub Secrets
          MONGO_URL: ${{ secrets.MONGO_URL }}      # Sử dụng MONGO_URL từ GitHub Secrets
          REDIS_URL: ${{ secrets.REDIS_URL }}      # Sử dụng REDIS_URL từ GitHub Secrets
